// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmslyvjddbdzzlpojoew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tc2x5dmpkZGJkenpscG9qb2V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMjc5NDksImV4cCI6MjA2OTkwMzk0OX0.tQHaX7MKb7jHCBFwWEn1XDD4H4UZkM8xbJg5F4oRUSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});